<?php
	include($_SERVER['DOCUMENT_ROOT'] . '/aurum/controllers/config.php');
	include($_SERVER['DOCUMENT_ROOT'] . '/aurum/controllers/function.php');
	include($_SERVER['DOCUMENT_ROOT'] . '/aurum/controllers/security.php');

	$addressID = 1;
	$inpAddressL1 = 'WEBkAzIMFWoSVUuxK9W+fMgo67bAhH/z21unLN/23t4=';
	$inpAddressL2 = 'Tower IV';
	$inpCity = 'HiXFJQo6oFMj9P4/jjzEwA==';
	$inpZip = '15250';
	$accID = 5;

	if(isset($_POST['submit']))
	{	
		#get the name of the account that uploaded the receipt
		$sql_uploader = "SELECT accountFN, accountLN FROM accounts WHERE accountID = ?";
		$params_uploader = array($accID);
		$stmt_uploader = sqlsrv_query($con, $sql_uploader, $params_uploader);
		while($row = sqlsrv_fetch_array($stmt_uploader))
		{
			$accountFN = openssl_decrypt(base64_decode($row['accountFN']), $method, $password, OPENSSL_RAW_DATA, $iv);
			$accountLN = openssl_decrypt(base64_decode($row['accountLN']), $method, $password, OPENSSL_RAW_DATA, $iv);
			$accountName = $accountLN . ', ' . $accountFN;
		}

		$receiptRemarks = "Billing generated by " . $accountName;
		echo $receiptRemarks;
	}
?>
<html>
<head></head>
<body>
	<form method="POST">
		<input type="submit" id="submit" name="submit" value="submit">
	</form>
</body>
</html>