/* insert data into accounts table */

/* account username: janedoe, password: janedoe, position: managing partner */
INSERT INTO accounts (accountUsername, 
					accountPassword, 
					accountPhoto, 
					accountFN, 
					accountMN, 
					accountLN, 
					accountBirthDate, 
					accountSex, 
					accountSSSNo, 
					accountTINNo, 
					accountBIRNo, 
					accountHDMFNo, 
					accountEmail, 
					accountBaseRate, 
					accountStatus, 
					cstatusID, 
					positionID, 
					departmentID)
VALUES ('Gw6jfiwL5tyaOh/N/VpWXw==', 
		'Gw6jfiwL5tyaOh/N/VpWXw==', 
		NULL, 
		'bZrfYnvaJTXiqPNTfltLig==', 
		'n6RHVJVfFATh9PsZjyzW+w==', 
		'wkVqz6VVPjXTTWLlynm7Tg==', 
		'1992-12-12', 
		'F', 
		'lGiG/3IyvuK/WYym+NZrFA==', 
		'q3bslPIczddhbnpZDf9UKg==', 
		'4GlecytGXLYPkJtrrcTTWg==', 
		'0ICLiF9aSUW2DlX/RApdhg==', 
		'px9nTGClteWgy4EbLn59KrbB777C8QIFMSKX05fxBGw=', 
		'75.00','Active',1,1,1);

/* account username: johndoe, password: johndoe, position: human resource and finance */
INSERT INTO accounts (accountUsername, 
					accountPassword, 
					accountPhoto, 
					accountFN, 
					accountMN, 
					accountLN, 
					accountBirthDate, 
					accountSex, 
					accountSSSNo, 
					accountTINNo, 
					accountBIRNo, 
					accountHDMFNo, 
					accountEmail, 
					accountBaseRate, 
					accountStatus, 
					cstatusID, 
					positionID, 
					departmentID)
VALUES ('CAGRf6f2JlRR+6IXe3ELIA==', 
		'CAGRf6f2JlRR+6IXe3ELIA==', 
		NULL, 
		'vR1MXzhRMZSnhO8iFg2CVA==', 
		'n6RHVJVfFATh9PsZjyzW+w==', 
		'm+nbNbYa1XlvVNVq46V/2A==', 
		'1992-04-22', 
		'M', 
		'lGiG/3IyvuK/WYym+NZrFA==', 
		'q3bslPIczddhbnpZDf9UKg==', 
		'4GlecytGXLYPkJtrrcTTWg==', 
		'0ICLiF9aSUW2DlX/RApdhg==', 
		'aynEyv+76pwMgIH0s3VJAXc3r/W6wD/+wdT+DbuvARg=', 
		'75.00','Active',1,8,4);